name: Generate PDF from Markdown

permissions:
  contents: read
  packages: read

on:
  push:
    paths:
      - "**.md"
      - "**.json"
      - "**.yml"
      - "**.yaml"
  pull_request:
    branches:
      - main
      - master
    paths:
      - "**.md"
      - "**.yml"
      - "**.yaml"
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run converter via Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/ARTIFACTS \
            ghcr.io/menta-epitech-academy/mdconverter:main \
            -t CC

      - name: Upload the output as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: markdown-converted
          path: ARTIFACTS/output