name: Generate PDF from Markdown

permissions:
  contents: read
  packages: read

on:
  push:
    paths:
      - "**.md"
      - "**.json"
      - "**.yml"
      - "**.yaml"
  pull_request:
    branches:
      - main
      - master
    paths:
      - "**.md"
      - "**.yml"
      - "**.yaml"
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin


      - name: Run converter via Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/ARTIFACTS \
            ghcr.io/menta-epitech-academy/mdconverter:main 

      - name: Find the generated PDF file
        id: find_pdf
        run: |
          pdf_path=$(find . -type f -name '*.pdf' | head -n 1)
          echo "PDF found at: $pdf_path"
          echo "pdf_path=$pdf_path" >> $GITHUB_OUTPUT

      - name: Upload the PDF to the release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.find_pdf.outputs.pdf_path }}
          asset_name: output.pdf
          asset_content_type: application/pdf