name: Generate PDF from Markdown

on:
  push:
    paths:
      - "**.md"
      - "**.json"
      - "**.yml"
      - "**.yaml"
  pull_request:
    branches:
      - main
      - master
    paths:
      - "**.md"
      - "**.yml"
      - "**.yaml"
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Convert markdown to PDF and HTML
        using: docker
        image: docker://ghcr.io/menta-epitech-academy/docker-md-converter:main

