name: Generate PDF from Markdown

on:
  push:
    paths:
      - "**.md"
      - "**.json"
      - "**.yml"
      - "**.yaml"
  pull_request:
    branches:
      - main
      - master
    paths:
      - "**.md"
      - "**.yml"
      - "**.yaml"
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run converter via Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/data \
            ghcr.io/menta-epitech-academy/docker-md-converter:main 