name: Generate PDF from Markdown

on:
  push:
    paths:
      - "**.md"
      - "**.json"
      - "**.yml"
      - "**.yaml"
  pull_request:
    branches:
      - main
      - master
    paths:
      - "**.md"
      - "**.yml"
      - "**.yaml"
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Convert markdown to PDF and HTML
        uses: menta-epitech-academy/md-converter@v1
